### ISSUE TITLE
Getting RuntimeError when use team.roster(1) or league.player_stats([0],'season')

### ISSUE THREAD

**Issue by CarlosChen1126** [spilchen/yahoo_fantasy_api#25]
Hi, I want to ask a question I've faced. I get RuntimeError continuously when I use team.roster(1) and league.player_stats([0],'season'). My goal is to get every player's stats and make a .csv file.(I'm sure that I have exactly login)
This is my code:
```python
from yahoo_oauth import OAuth2
import yahoo_fantasy_api as yfa
import json


sc = OAuth2(None, None, from_file='./varify.json')
gm = yfa.Game(sc, 'mlb')

ids = gm.league_ids(year=2021)

lg = gm.to_league(ids[1])
team_key = lg.team_key()
team = lg.to_team(team_key[0])
print(team.roster(1))
```

and this is the error message
```python
[2021-07-22 04:23:40,810 DEBUG] [yahoo_oauth.oauth.__init__] Checking 
[2021-07-22 04:23:40,810 DEBUG] [yahoo_oauth.oauth.token_is_valid] ELAPSED TIME : 816.7230370044708
[2021-07-22 04:23:40,810 DEBUG] [yahoo_oauth.oauth.token_is_valid] TOKEN IS STILL VALID
Traceback (most recent call last):
  File "fantasy_api.py", line 14, in <module>
    print(team.roster(1))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yahoo_fantasy_api/team.py", line 69, in roster
    t = objectpath.Tree(self.yhandler.get_roster_raw(self.team_key,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yahoo_fantasy_api/yhandler.py", line 119, in get_roster_raw
    return self.get("team/{}/roster{}".format(team_key, param))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yahoo_fantasy_api/yhandler.py", line 25, in get
    raise RuntimeError(response.content)
RuntimeError: b'{\n    "error": {\n        "xml:lang": "en-us",\n        "yahoo:uri": "\\/fantasy\\/v2\\/team\\/4\\/roster;week=1?format=json",\n        "description": "Missing Resource ID for team",\n        "detail": ""\n    }\n}'
```
Thanks for your help! I am desired to know how to deal with this error!

**Comment by DMcP89** [comment]
The return type of lg.team_key() is a string not an array.  So instead of:
```
team = lg.to_team(team_key[0])
```
Try:
```
team = lg.to_team(team_key)
```

Here's the full method definition for context:
```
    def team_key(self):
        """Return the team_key for logged in users team in this league
        :return: The team key
        :rtype: str
        >>> lg.team_key()
        388.l.27081.t.5
     https://github.com/spilchen/yahoo_fantasy_api/blob/master/yahoo_fantasy_api/league.py#L198   """
        t = objectpath.Tree(self.yhandler.get_teams_raw())
        json = t.execute('$..(team_key)')
        for t in json:
            if t['team_key'].startswith(self.league_id):
                return t['team_key']
```
https://github.com/spilchen/yahoo_fantasy_api/blob/master/yahoo_fantasy_api/league.py#L198

**Comment by DMcP89** [comment]
@spilchen  Believe this can be closed.
